# Generated by Django 3.2 on 2022-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('c', 'careem'), ('t', 'talabat'), ('cs', 'csmena'), ('sk', 'ask paper')], max_length=2)),
                ('brand', models.CharField(max_length=100)),
                ('fulfillment_partner', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=7, max_digits=10)),
                ('delivery_zone', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile_number', models.IntegerField()),
            ],
        ),
    ]
